/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author kieef
 */
public class frmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmCategory
     */
    
    frmStaff frmStaff;
    frmCate frmCate;
    
    //boolean full_screen = frmLogIn.full_screen;
    
    public frmAdmin() {
        initComponents();
        
        ImageIcon img = new ImageIcon(frmLogIn.iconPath);
        setIconImage(img.getImage());
        
        if (frmLogIn.full_screen == true)
        {  
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        else
        {
            setSize(794,612);
        }
        
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnStaff = new javax.swing.JButton();
        btnCate = new javax.swing.JButton();
        btnDish = new javax.swing.JButton();
        btnCombo = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FOOD COURT - ADMIN");
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(100, 100));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(207, 244, 210));
        jPanel1.setPreferredSize(new java.awt.Dimension(809, 612));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnMenu.setBackground(new java.awt.Color(237, 163, 35));
        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("MENU");
        btnMenu.setBorderPainted(false);
        btnMenu.setMaximumSize(new java.awt.Dimension(75, 60));
        btnMenu.setMinimumSize(new java.awt.Dimension(75, 60));
        btnMenu.setPreferredSize(new java.awt.Dimension(75, 60));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenu);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnStaff.setBackground(new java.awt.Color(237, 163, 35));
        btnStaff.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnStaff.setText("STAFF");
        btnStaff.setBorderPainted(false);
        btnStaff.setMaximumSize(new java.awt.Dimension(75, 60));
        btnStaff.setMinimumSize(new java.awt.Dimension(75, 60));
        btnStaff.setPreferredSize(new java.awt.Dimension(75, 60));
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });
        jPanel3.add(btnStaff);

        btnCate.setBackground(new java.awt.Color(237, 163, 35));
        btnCate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCate.setForeground(new java.awt.Color(255, 255, 255));
        btnCate.setText("CATE");
        btnCate.setBorderPainted(false);
        btnCate.setMaximumSize(new java.awt.Dimension(75, 60));
        btnCate.setMinimumSize(new java.awt.Dimension(75, 60));
        btnCate.setPreferredSize(new java.awt.Dimension(75, 60));
        btnCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateActionPerformed(evt);
            }
        });
        jPanel3.add(btnCate);

        btnDish.setBackground(new java.awt.Color(237, 163, 35));
        btnDish.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDish.setForeground(new java.awt.Color(255, 255, 255));
        btnDish.setText("DISH");
        btnDish.setBorderPainted(false);
        btnDish.setMaximumSize(new java.awt.Dimension(75, 60));
        btnDish.setMinimumSize(new java.awt.Dimension(75, 60));
        btnDish.setPreferredSize(new java.awt.Dimension(75, 60));
        jPanel3.add(btnDish);

        btnCombo.setBackground(new java.awt.Color(237, 163, 35));
        btnCombo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCombo.setForeground(new java.awt.Color(255, 255, 255));
        btnCombo.setText("COMBO");
        btnCombo.setBorderPainted(false);
        btnCombo.setMaximumSize(new java.awt.Dimension(75, 60));
        btnCombo.setMinimumSize(new java.awt.Dimension(75, 60));
        btnCombo.setPreferredSize(new java.awt.Dimension(75, 60));
        jPanel3.add(btnCombo);

        btnCustomer.setBackground(new java.awt.Color(237, 163, 35));
        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setText("CUSTOMER");
        btnCustomer.setBorderPainted(false);
        btnCustomer.setMaximumSize(new java.awt.Dimension(75, 60));
        btnCustomer.setMinimumSize(new java.awt.Dimension(75, 60));
        btnCustomer.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel3.add(btnCustomer);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jDesktopPane1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame frmChild : jDesktopPane1.getAllFrames()) {
            frmChild.dispose();
        }
        
        if(frmStaff == null || frmStaff.isClosed())
        {
            try {
                frmStaff = new frmStaff();
            } catch (SQLException ex) {
                Logger.getLogger(frmAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            jDesktopPane1.add(frmStaff);
            frmStaff.setSize(this.getWidth(),this.getHeight());
            frmStaff.setLocation(0,0);
            frmStaff.setVisible(true);
            }
            else
            {
            
                frmStaff.setSize(this.getWidth(),this.getHeight());
                frmStaff.setLocation(0,0);
                frmStaff.setVisible(true);
        }
        
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame frmChild : jDesktopPane1.getAllFrames()) {
            frmChild.dispose();
        }
        
        if(frmCate == null || frmCate.isClosed())
        {
            frmCate = new frmCate();
            jDesktopPane1.add(frmCate);
            frmCate.setSize(this.getWidth(),this.getHeight());
            frmCate.setLocation(0,0);
            frmCate.setVisible(true);
            }
            else
            {
            
                frmCate.setSize(this.getWidth(),this.getHeight());
                frmCate.setLocation(0,0);
                frmCate.setVisible(true);
        }
    }//GEN-LAST:event_btnCateActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frmMenu().setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        if (frmLogIn.full_screen == true)
        {
            frmLogIn.full_screen = false;
        }
        else
        {
            frmLogIn.full_screen = true;
        }
        
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCate;
    private javax.swing.JButton btnCombo;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnDish;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnStaff;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
