/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.event.MouseListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Interface.frmAdmin_Customer;
import Process.Category;

import java.sql.ResultSet;
import java.sql.SQLException;
import Process.Dish;//Lớp Dish trong Proccess đã thực hiện
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author kieef
 */
public class frmAdmin_Dish extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmStaff
     */
    private final Category cate = new Category();
    public frmAdmin_Dish() throws SQLException {
        initComponents();
        this.txtDID. setEnabled (false);
        
        setTitle("DISH PAGE");
        
        BasicInternalFrameUI bs = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI());
        for (MouseListener l: bs.getNorthPane().getMouseListeners()){
            bs.getNorthPane().removeMouseListener(l);
        }
        
        String []colsName = {"ID Dish", "Name", "Price", "Category" };
        // đặt tiêu đề cột cho tableModel
        tableModel.setColumnIdentifiers(colsName);
        // kết nối jtable với tableModel
        tableDish.setModel(tableModel);
        tableDish.setDefaultEditor(Object.class, null);
        //gọi hàm ShowData để đưa dữ liệu vào tableModel
        ResultSet result = lsp.Dish();
        ShowData(result);
        //goi Ham xoa trang cac TextField
        setNull();
        //Goi ham Khoa cac TextField
        setKhoa(true);
        //Goi vo hieu 2 button Luu, K.Luu. Mo khoa 4 button con lao
        setButton("");
        
        AutoCompleteDecorator.decorate(cbCate);
        GetCate();
    }

//    frmDish(String msg) {
//      initComponents();
//      id.setText();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbCate = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDish = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(100, 563));
        setMinimumSize(new java.awt.Dimension(100, 563));
        setNextFocusableComponent(this);
        setPreferredSize(new java.awt.Dimension(809, 536));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMATION"));

        jLabel1.setText(" Dish ID ");

        jLabel2.setText("Name");

        jLabel3.setText("Dish Price");

        txtDID.setEnabled(false);
        txtDID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDIDActionPerformed(evt);
            }
        });

        jLabel4.setText("Category");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDID)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrice)
                    .addComponent(cbCate, 0, 180, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtDID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel10.setLayout(new java.awt.BorderLayout());

        tableDish.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Dish", "Name", "Price", "Category"
            }
        ));
        tableDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDishMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDish);

        jPanel10.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel8.setPreferredSize(new java.awt.Dimension(807, 90));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnAdd.setBackground(new java.awt.Color(237, 163, 35));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setBorderPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnEdit.setBackground(new java.awt.Color(237, 163, 35));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.setBorderPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit);

        btnSave.setBackground(new java.awt.Color(237, 163, 35));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave);

        btnClear.setBackground(new java.awt.Color(237, 163, 35));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.setBorderPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);

        btnDelete.setBackground(new java.awt.Color(237, 163, 35));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.setBorderPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);

        jPanel8.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("SEARCH"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        btnSearch.setBackground(new java.awt.Color(237, 163, 35));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.setBorderPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, java.awt.BorderLayout.LINE_END);

        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        jPanel3.add(txtSearch, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDIDActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        ResultSet result = null;
        try {
            result = lsp.Dish();
        } catch (SQLException ex) {
            Logger.getLogger(frmAdmin_Dish.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ShowData(result);
        } catch (SQLException ex) {
            Logger.getLogger(frmAdmin_Dish.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setNull();
        setKhoa(true);
        setButton("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tableDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDishMouseClicked
        // TODO add your handling code here:
        try{
        //Lay chi so dong dang chon
            int row = this.tableDish.getSelectedRow(); //lỗi xàm ghê á :)))) laf seo

            int ml=Integer.parseInt((this.tableDish.getModel().getValueAt(row,0)).toString());

            ResultSet rs= lsp.Dish_ID(ml);//Goi ham lay du lieu theo ma loai

            if(rs.next())//Neu co du lieu
            {
                txtDID.setText(rs.getString(1));
                this.txtName.setText(rs.getString(2));
                this.txtPrice.setText(rs.getString(3));///name nằm ở vị trí 2 trong kết quả trả về của sqlok
                int cate_id = Integer.parseInt(rs.getString(4)) ;
                String cate_name = ConvertCateBack(cate_id);
                cbCate.setSelectedItem(cate_name);
            }
            setButton("clicked");
        }
        catch (SQLException e) {
            
        } 
    }//GEN-LAST:event_tableDishMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        setNull();//Xoa trang TextField
        setKhoa(false);//Mo khoa TextField
        setButton("add");//Goi ham khoa cac Button
        cothem=true;//Gan cothem = true de ghi nhan trang thai them moi
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String tl=txtName.getText();
        System.out.println("Name: "+tl);
        if(!CheckInput()) //nếu có ô trống
            JOptionPane.showMessageDialog(null,"Vui long chon loi can sua","Thong bao",1);
        else
        {
        setKhoa(false);//Mo khoa cac TextField
        setButton("edit"); //Khoa cac Button
        cothem=false; //Gan cothem=false de ghi nhan trang thai la sua
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // String Id= Id.setID(Id);

        String name=txtName.getText();
        String gia=txtPrice.getText();
        
        if (name.trim().isEmpty() || gia.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill out the blank");
        }
        else
        {
            String cate_name  = cbCate.getSelectedItem().toString();
            try {
                int cate_id = ConvertCate(cate_name);
                long price = Long.parseLong(gia);
                if(!CheckInput())
                JOptionPane.showMessageDialog(null,"Vui long nhap Ten mon an va gia","Thong bao",1);
                else
                { 
    //           
                try {
                if(cothem==true){ //Luu cho tthem moi

                    lsp.InsertDish(name,price,cate_id);
                    JOptionPane.showMessageDialog(null,"Them thanh cong","Thong bao",1);
                }
                else //Luu cho sua
                {
                    int d_id= Integer.parseInt(txtDID.getText()); /// truyền cái id vô làm gì ?
                    lsp.EditDish(d_id,name , price,cate_id);
                    JOptionPane.showMessageDialog(null,"Sua thanh cong","Thong bao",1);
                }
                //ClearData(); //goi ham xoa du lieu tron tableModel
                ResultSet result = lsp.Dish();
                ShowData(result); //Do lai du lieu vao Table Model
                
                setKhoa(false);

                setButton("save");
                
                setNull();
                setKhoa(true);
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Cap nhat that bai","Thong bao",1);
                }          
                }
            } catch (SQLException ex) {

            } catch (NumberFormatException n)
            {
                JOptionPane.showMessageDialog(this, "Price is number");
            }

        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String ml=txtDID.getText();
//        int ml= Integer.parseInt(txtID.getText());
        try {
        if(ml.length()==0)
            JOptionPane.showMessageDialog(null,"Chon 1 mon ăn de xoa","Thong bao",1);
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Ban muon xoa mon " + ml + " nay hay khong?","Thong bao",2)==0)
            {
                int bien = Integer.parseInt(ml);
                lsp.DeleteDish(bien);//goi ham xoa du lieu theo ma loai
                //ClearData();//Xoa du lieu trong tableModel
                ResultSet result = lsp.Dish();
                ShowData(result);//Do du lieu vao table Model ủa nó nè :))))
                setNull();//Xoa trang Textfield
            }
            
        }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Xóa thất bại","Thong bao",1);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void Search(String i)
    {
        try {
           
            tableModel.setRowCount(0);
            ResultSet result = lsp.Dish_Name(i);
            ShowData(result);
            
        } catch (SQLException ex) {
            Logger.getLogger(frmAdmin_Dish.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
//        ResultSet result= lsp.Dish_ID(WIDTH)
//        if(result.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
//        txtTenloai.setText(result.getString("Tenloai"));
        String i = txtSearch.getText();       
        if (i.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Search fill is blank");
        }
        else
        {
            Search(i);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        String i = txtSearch.getText(); 
        Search(i);
    }//GEN-LAST:event_txtSearchKeyPressed

    
     // Xử lý hiện thị dữ liệu khi Form được mở
//    String id= frmCustomer.txtID.getText();
    private final Dish lsp = new Dish();
    private boolean cothem=true;
    private final DefaultTableModel tableModel = new DefaultTableModel();
    
    //Ham do du lieu vao tableModel
    public void ShowData(ResultSet result) throws SQLException{
        tableModel.getDataVector().removeAllElements(); ///refresh lại model
        try {
                while(result.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[4];
                rows[0] = result.getString(1); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
                rows[1] = result.getString(2);
                rows[2] = result.getString(3);// lấy dữ liệu tai cột số 2 ứng với tên hàng
                int cate_id = Integer.parseInt(result.getString(4));
                String cate_name = ConvertCateBack(cate_id);
                rows[3] = cate_name;
                tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel
                //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update
                }
            }
        catch (SQLException e) {
            }
    }
    //Ham xoa du lieu trong tableModel
    public void ClearData() throws SQLException{
        //Lay chi so dong cuoi cung
        int n=tableDish.getRowCount()-1;
        for(int i=n;i>=0;i--)
        tableDish.remove(i);//Remove tung dong
    } 
    //Ham xoa cac TextField
    private void setNull(){ 
        //Xoa trang cac JtextField
        this.txtDID.setText(null);
        this.txtName.setText(null);
        this.txtPrice.setText(null);
    }
    //Ham khoa cac TextField
    private void setKhoa(boolean a)
    {
        //Khoa hoac mo khoa cho Cac JTextField
        this.txtName.setEnabled (!a);
        this.txtPrice.setEnabled (!a);

    } 
     //Ham khoa cac Button
    private void setButton(String a){
        //Vo hieu hoac co hieu luc cho cac JButton
        switch (a) {
            case "add":
                this.btnAdd. setEnabled (true);
                this.btnDelete. setEnabled (false);
                this.btnEdit. setEnabled (false);
                this.btnSave. setEnabled (true);
                break;
            case "edit":
                this.btnAdd. setEnabled (false);
                this.btnDelete. setEnabled (false);
                this.btnSave. setEnabled (true);
                break;
            case "save":
                this.btnAdd. setEnabled (false);
                this.btnDelete. setEnabled (false);
                this.btnEdit. setEnabled (false);
                setNull();
                break;
            case "clicked":
                this.btnAdd. setEnabled (false);
                this.btnDelete. setEnabled (true);
                this.btnEdit. setEnabled (true);
                break;
            default:
                this.btnAdd. setEnabled (true);
                this.btnDelete. setEnabled (false);
                this.btnEdit. setEnabled (false);
                this.btnSave. setEnabled (false);
                break;
        }
    }
    private boolean CheckInput()
    {
        String name = txtName.getText();
        String price = txtPrice.getText();
        if( name.isBlank() || name.isEmpty())
        {
            return false;
        }
        else if( price.isBlank() || price.isEmpty())
        {
            return false;
        }
        return true;
    }
    private void GetCate()
    {
         try {
            
            ResultSet result= cate.Category();
            while(result.next()){ 
                String name = result.getString(2); 
                cbCate.addItem(name);
            }
        }
        catch (SQLException e) {
        }
    }
    private int ConvertCate(String name) throws SQLException
    {
        int cate_id =-1;
        ResultSet rs = cate.Category();
        while(rs.next()){ 
                String Cate_name = rs.getString(2); 
                if(name.equalsIgnoreCase(Cate_name))
                {
                    cate_id = Integer.parseInt(rs.getString(1)) ;
                    break;
                }
        }
        return cate_id;
    }
    private String ConvertCateBack(int id) throws SQLException
    {
        String name="";
        ResultSet rs = cate.Category();
        while(rs.next()){ 
                int Cate_id = Integer.parseInt(rs.getString(1)) ; 
                if(id == Cate_id)
                {
                    name = rs.getString(2) ;
                    break;
                }
        }
        return name;
    }
    public static void main(String args[]) throws SQLException {

        frmAdmin_Dish s = new frmAdmin_Dish();
        s.setVisible(true);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbCate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDish;
    private javax.swing.JTextField txtDID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
