package Interface;


import Process.Dish;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kieef
 */
public class frmReport_DishSold extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReport_DishSold
     */
    
    
    private final DefaultTableModel tableDish = new DefaultTableModel();
    String get_date = "";
    Dish dish = new Dish();
    
    public frmReport_DishSold() throws SQLException {
        initComponents();
        setTitle("DISH SOLD PAGE");
        
        BasicInternalFrameUI bs = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI());
        for (MouseListener l: bs.getNorthPane().getMouseListeners()){
            bs.getNorthPane().removeMouseListener(l);
        }
        
        ///setting for tbCate
        String []colsName_Cate = {"Dish ID","Dish Name","Quantity"};
        // đặt tiêu đề cột cho tableModel
        tableDish.setColumnIdentifiers(colsName_Cate);
        tbDish.setModel(tableDish);
        tbDish.getColumnModel().getColumn(0).setWidth(0);
        tbDish.getColumnModel().getColumn(0).setMinWidth(0);
        tbDish.getColumnModel().getColumn(0).setMaxWidth(0);        
        tbDish.setDefaultEditor(Object.class, null);
        
        ///giá trị sort: 1 là tăng, 0 là giảm
        LocalDateTime now = LocalDateTime.now().minus(Period.ofDays( 30 ));  
        DateTimeFormatter date_f = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
        get_date = date_f.format(now);
        
        DishSort(get_date,0);
        
        ButtonGroup G = new ButtonGroup();
        G.add(rdIncr);
        G.add(rdDec);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rdIncr = new javax.swing.JRadioButton();
        rdDec = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDish = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setMinimumSize(new java.awt.Dimension(393, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(693, 120));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(373, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(373, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(373, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("SEARH"));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btnClear.setBackground(new java.awt.Color(237, 163, 35));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.setBorderPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(237, 163, 35));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.setBorderPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("SORT"));

        rdIncr.setBackground(new java.awt.Color(255, 255, 255));
        rdIncr.setText("Price increasing");
        rdIncr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdIncrMouseClicked(evt);
            }
        });
        jPanel5.add(rdIncr);

        rdDec.setBackground(new java.awt.Color(255, 255, 255));
        rdDec.setText("Price decreasing");
        rdDec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdDecMouseClicked(evt);
            }
        });
        jPanel5.add(rdDec);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setPreferredSize(new java.awt.Dimension(472, 382));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tbDish.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dish ID", "Dish Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDish);
        if (tbDish.getColumnModel().getColumnCount() > 0) {
            tbDish.getColumnModel().getColumn(0).setMinWidth(0);
            tbDish.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbDish.getColumnModel().getColumn(0).setMaxWidth(0);
            tbDish.getColumnModel().getColumn(1).setResizable(false);
            tbDish.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void DishSort (String date,int sort) throws SQLException
    {
        tableDish.getDataVector().removeAllElements();
        ResultSet rs= dish.DishSold(date,sort);
        try {
            while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[3];
            rows[0] = rs.getString(1); // dishID
            rows[2] = rs.getString(2); // Quantity
            rows[1] = rs.getString(3); // Dish name
            tableDish.addRow(rows); // đưa dòng dữ liệu vào tableModelDish
            //mỗi lần có sự thay đổi dữ liệu ở tableModelDish thì Jtable sẽ tự động update
            
            }
        }
        catch (SQLException e) {
        }
    }
    
    public void DishSearch ()
    {
        String search = txtSearch.getText(); 
        
        if (search.trim() != null)
        {
            tableDish.getDataVector().removeAllElements();
            try {
                ResultSet rs= dish.DishSearch(search, get_date);
                while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[3];
                rows[0] = rs.getString(1); // dishID
                rows[2] = rs.getString(2); // Quantity
                rows[1] = rs.getString(3); // Dish name
                tableDish.addRow(rows); // đưa dòng dữ liệu vào tableModelDish
                //mỗi lần có sự thay đổi dữ liệu ở tableModelDish thì Jtable sẽ tự động update

                }
            }
            catch (SQLException e) {
            }
        }
    }
    private void rdIncrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdIncrMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DishSort(get_date,1);
        } catch (SQLException ex) {
            Logger.getLogger(frmReport_DishSold.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rdIncrMouseClicked

    private void rdDecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdDecMouseClicked
        try {
            // TODO add your handling code here:
            DishSort(get_date,0);
        } catch (SQLException ex) {
            Logger.getLogger(frmReport_DishSold.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rdDecMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtSearch.setText("");
        if (rdDec.isSelected())
        {
            try {
                DishSort(get_date,0);
            } catch (SQLException ex) {
                Logger.getLogger(frmReport_DishSold.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (rdIncr.isSelected())
        {
            try {
                DishSort(get_date,1);
            } catch (SQLException ex) {
                Logger.getLogger(frmReport_DishSold.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else 
        {
            try {
                DishSort(get_date,0);
            } catch (SQLException ex) {
                Logger.getLogger(frmReport_DishSold.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        DishSearch();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        DishSearch();
    }//GEN-LAST:event_txtSearchKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdDec;
    private javax.swing.JRadioButton rdIncr;
    private javax.swing.JTable tbDish;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
