/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package week4;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author kieef
 */
public class bt4_JList_CheckBox extends javax.swing.JFrame {

    /**
     * Creates new form bt4_JList_CheckBox
     */
    
    DefaultListModel listModel = new DefaultListModel();
    int n;
    int[] index_s;
    
    public bt4_JList_CheckBox() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnChan = new javax.swing.JButton();
        btnLe = new javax.swing.JButton();
        btnSNT = new javax.swing.JButton();
        btnBoDen = new javax.swing.JButton();
        btnXoaDen = new javax.swing.JButton();
        btnTong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNumber = new javax.swing.JTextField();
        btnNhap = new javax.swing.JButton();
        ckAm = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsNumber = new javax.swing.JList<>();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thao tác trên JList");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THAO TÁC TRÊN JLIST - CHECKBOX");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CHỌN TÁC VỤ"));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        btnChan.setText("Tô đen số chẵn");
        btnChan.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnChan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChanActionPerformed(evt);
            }
        });
        jPanel3.add(btnChan);

        btnLe.setText("Tô đen số lẻ");
        btnLe.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnLe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeActionPerformed(evt);
            }
        });
        jPanel3.add(btnLe);

        btnSNT.setText("Tô đen số nguyên tố");
        btnSNT.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnSNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSNTActionPerformed(evt);
            }
        });
        jPanel3.add(btnSNT);

        btnBoDen.setText("Bỏ tô đen");
        btnBoDen.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnBoDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoDenActionPerformed(evt);
            }
        });
        jPanel3.add(btnBoDen);

        btnXoaDen.setText("Xóa các giá trị đang tô đen");
        btnXoaDen.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnXoaDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDenActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoaDen);

        btnTong.setText("Tổng giá trị trong JList");
        btnTong.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongActionPerformed(evt);
            }
        });
        jPanel3.add(btnTong);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("NHẬP THÔNG TIN"));

        btnNhap.setText("NHẬP");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        ckAm.setText("Cho nhập số âm");

        jScrollPane1.setViewportView(lsNumber);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ckAm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhap)
                    .addComponent(ckAm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        btnClose.setText("ĐÓNG CHƯƠNG TRÌNH");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///kiểm tra số nguyên tố
    public boolean SNT(int a)
    {
        if (a == 1) return true;
        for (int i = 2; i < a; i++) {
            if (a % i == 0) return false;
        }
        return true;
    }
    
    ///kiểm tra số chẳn
    public boolean Even(int a)
    {
        if (a%2 == 0)
            return true;
        return false;
    }
    
    ///kiểm tra số lẻ
    public boolean Odd(int a)
    {
        if (a%2 != 0)
            return true;
        return false;
    }
    
    ///thêm vào list
    public void addList(int num)
    {
        lsNumber.setModel(listModel);
        listModel.addElement(num);
        
        n = lsNumber.getModel().getSize();
    }
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:
        try
        {
            int num = Integer.parseInt(txtNumber.getText());
            
            if (!ckAm.isSelected())
            {
                if (num < 0)
                    JOptionPane.showMessageDialog(this, "Không được nhập số âm");
                else
                {
                    addList(num);
                }
            }
            else 
            {
                addList(num);
            }
        }
        catch (NumberFormatException e)
        {
             JOptionPane.showMessageDialog(this, "Đừng có nhập chữ má ôi");
        }
        txtNumber.setText("");
    }//GEN-LAST:event_btnNhapActionPerformed

    private void btnChanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChanActionPerformed
        // TODO add your handling code here:
        index_s = new int[n];
        int index_i = 0;
        
        for (int i = 0; i < n; i++) 
        {
            String valuex = String.valueOf(lsNumber.getModel().getElementAt(i));
            int this_num = Integer.parseInt(valuex);
            if (Even(this_num))
            {
                index_s[index_i] = i ;
                index_i = index_i + 1 ;
            }
        }
        
        lsNumber.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        lsNumber.setSelectedIndices(index_s);
        lsNumber.setSelectionBackground(Color.gray);
    }//GEN-LAST:event_btnChanActionPerformed

    private void btnLeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        index_s = new int[n];
        int index_i = 0;
        
        for (int i = 0; i < n; i++) 
        {
            String valuex = String.valueOf(lsNumber.getModel().getElementAt(i));
            int this_num = Integer.parseInt(valuex);
            if (Odd(this_num))
            {
                index_s[index_i] = i ;
                index_i = index_i + 1 ;
            }
        }
        
        lsNumber.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        lsNumber.setSelectedIndices(index_s);
        lsNumber.setSelectionBackground(Color.gray);
    }//GEN-LAST:event_btnLeActionPerformed

    private void btnSNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSNTActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        index_s = new int[n];
        int index_i = 0;
        
        for (int i = 0; i < n; i++) 
        {
            String valuex = String.valueOf(lsNumber.getModel().getElementAt(i));
            int this_num = Integer.parseInt(valuex);
            if (SNT(this_num))
            {
                index_s[index_i] = i ;
                index_i = index_i + 1 ;
            }
        }
        
        lsNumber.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        lsNumber.setSelectedIndices(index_s);
        lsNumber.setSelectionBackground(Color.gray);
    }//GEN-LAST:event_btnSNTActionPerformed

    private void btnBoDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoDenActionPerformed
        // TODO add your handling code here:
        lsNumber.setSelectedIndices(index_s);
        lsNumber.setSelectionBackground(Color.white);
    }//GEN-LAST:event_btnBoDenActionPerformed

    private void btnXoaDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDenActionPerformed
        // TODO add your handling code here
        for (int i = 0; i < n; i++)
        {
            for (int j = 0; j < index_s.length; j++) {
                if(index_s[j] == i)
                {
                    listModel.removeElementAt(index_s[i]);
                    n = n - 1;
                }
            }
        }
    }//GEN-LAST:event_btnXoaDenActionPerformed

    private void btnTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bt4_JList_CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bt4_JList_CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bt4_JList_CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bt4_JList_CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bt4_JList_CheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoDen;
    private javax.swing.JButton btnChan;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLe;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSNT;
    private javax.swing.JButton btnTong;
    private javax.swing.JButton btnXoaDen;
    private javax.swing.JCheckBox ckAm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lsNumber;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
